In [2]:
import numpy as np
# numpy属性
array = np.array([[1, 2, 3], [2, 3, 4]])
print(array)
print("dimension of array: {}".format(array.ndim))  # 维度
print("shape of array: {}".format(array.shape))  # 行数和列数
print("size of array: {}".format(array.size))  # 元素个数

[[1 2 3]
 [2 3 4]]
dimension of array: 2
shape of array: (2, 3)
size of array: 6


In [3]:
# numpy指定数据dtype
a = np.array([2, 3, 4], dtype=np.int)
print(a.dtype)
b = np.array([1, 2, 3], dtype=np.float)
print(b.dtype)
c = np.array([3, 4, 5], dtype=np.int32)
print(c.dtype)
d = np.array([5, 6, 7], dtype=np.float32)
print(d.dtype)

int64
float64
int32
float32


In [40]:
# numpy创建指定数据
a = np.array([[1, 2, 3], [2, 3, 4]])
print(a)
# 创建全0数组
a = np.zeros((3, 2))
print(a)
# 创建全1数组，指定数据类型
a = np.ones((3, 2), dtype=np.int)
print(a)
# 创建空数组，每个值都接近0
a = np.empty((3, 4))
print(a)
# 创建连续数组
a = np.arange(10, 20, 2)  # np.arange([begin,]end[,step])  [begin, end)
print(a)
# 改变形状
a = np.arange(12).reshape((3, 4))
print(a)
# 创建线段型数据
a = np.linspace(1, 10, 20)  # np.linspace(begin, end, num)  [begin, end]
print(a)
b = a.reshape((5, 4))
print(b)
# 创建随机矩阵
a = np.random.random((2, 4))
print(a)

[[1 2 3]
 [2 3 4]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 1]
 [1 1]
 [1 1]]
[[0.93243211 0.1749326  0.67232838 0.47884234]
 [0.36753946 0.40500412 0.99411914 0.57625735]
 [0.76069719 0.54476337 0.73671924 0.13790724]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
[[0.5421761  0.84461869 0.79889601 0.39783591]
 [0.5277078  0.31615336 0.66005626 0.01134943]]


In [108]:
# numpy基本运算1
a = np.array((2, 3))
print(a)
b = np.array((2, 3))
print(b)
# 加
c = a + b  # (1)
print(c)
c = np.add(a, b)  # (2)
print(c)
np.add(a, b, out=c)  # (3)
print(c)
# 效率(3) > (2) > (1)
# 减
c = a - b
print(c)
# 对应位置元素相乘
c = a * b
print(c)
# 各个元素乘方
c = a ** 2
print(c)
# 三角函数
c = 10 * np.sin(a)
print(c)
# 逻辑判断
print(c < 3)
# 矩阵乘(两种表达形式)
c_dot = np.dot(a, b)
print(c_dot)
c_dot = a.dot(b)
print(c_dot)

[2 3]
[2 3]
[4 6]
[4 6]
[4 6]
[0 0]
[4 9]
[4 9]
[9.09297427 1.41120008]
[False  True]
13
13


In [102]:
# numpy基本运算2
# max,min,sum
a = np.array([[1, 2, 3], [2, 3, 4]])
print(a)
print(a.sum())  # np.sum(a)
print(a.max())  # np.max(a)
print(a.min())  # np.min(a)
# axis=0 以列为查找单元
# axis=1 以行为查找单元
print(a.sum(axis=1))  # np.sum(a, axis=1)
# 最小元素索引
print(a.argmin())  # np.argmin(a)
# 最大元素索引
print(a.argmax())  # np.argmax(a)
# 求均值
print(a.mean())  # np.mean(a)
# 求中位数
print(np.median(a, axis=0))  # a.median() error
# cumsum()生成的每一项矩阵元素是从原矩阵首项累加到对应项的元素之和
print(np.cumsum(a))
# diff()生成的每一项矩阵元素是原矩阵每一行中后项与前项之差
print(np.diff(a))
# nonzero()将原矩阵中所有非零元素的行和列分开
print(np.nonzero(a))
# 行排序sort()
print(np.sort(a))
# 转置
print(np.transpose(a))
# clip(Array, Array_min, Array_max)将矩阵中小于Array_min的值转换为Array_min,
# 大于Array_max的值转换为Array_max
print(np.clip(a, 2, 3))

[[1 2 3]
 [2 3 4]]
15
4
1
[6 9]
0
5
2.5
[1.5 2.5 3.5]
[ 1  3  6  8 11 15]
[[1 1]
 [1 1]]
(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))
[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]
[[2 2 3]
 [2 3 3]]


In [105]:
# numpy索引
A = np.arange(3, 15)
print(A)
# 一维索引
print(A[-1])
A = A.reshape((3, 4))
print(A)
# 二维索引
print(A[1][1])
print(A[1,1])
print(A[1, 1:3])
# 逐行打印
for row in A:
    print(row)
# 逐列打印
for col in A:
    print(col)
# 迭代打印
for item in A.flatten():  # same as A.flat / A.ravel() 把原矩阵展开成一维
# 注：flatten()会进行深拷贝，ravel()会进行浅拷贝，后者效率更高
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
14
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
8
8
[8 9]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [88]:
# numpy array合并
A = np.array([1, 2, 3])
B = np.array([2, 3, 4])
# 上下合并
print(np.vstack((A, B)))
# 左右合并
print(np.hstack((A, B)))
# 行列向量转置
print(A[np.newaxis,:])  # 行向量
print(A[np.newaxis,:].shape)
print(A[:,np.newaxis])  # 列向量
print(A[:,np.newaxis].shape)
print(np.transpose(A))
# 多矩阵合并
A = A[:,np.newaxis]
B = B[:,np.newaxis]
D = np.concatenate((A, B, B, A), axis=0)
print(D)
D = np.concatenate((A, B, B, A), axis=1)
print(D)

[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]
[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)
[1 2 3]
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]]
[[1 2 2 1]
 [2 3 3 2]
 [3 4 4 3]]


In [96]:
# numpy array分割
A = np.arange(3, 15).reshape((3, 4))
print(A)
# 平均分割
# 纵向分割
print(np.split(A, 2, axis=1))
# 横向分割
print(np.split(A, 3, axis=0))
# 不平均分割
print(np.array_split(A, 3, axis=1))
# 列分割
print(np.hsplit(A, 4))
# 行分割
print(np.vsplit(A, 3))

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[array([[ 3,  4],
       [ 7,  8],
       [11, 12]]), array([[ 5,  6],
       [ 9, 10],
       [13, 14]])]
[array([[3, 4, 5, 6]]), array([[ 7,  8,  9, 10]]), array([[11, 12, 13, 14]])]
[array([[ 3,  4],
       [ 7,  8],
       [11, 12]]), array([[ 5],
       [ 9],
       [13]]), array([[ 6],
       [10],
       [14]])]
[array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]]), array([[ 5],
       [ 9],
       [13]]), array([[ 6],
       [10],
       [14]])]
[array([[3, 4, 5, 6]]), array([[ 7,  8,  9, 10]]), array([[11, 12, 13, 14]])]


In [100]:
# numpy copy & deep copy
# 使用=浅拷贝
a = np.arange(3, 15).reshape((3, 4))
print(a)
b = a
a[0, 0] = 2
print(a)
print(b)
print(b is a)  # => True
# 使用copy()深拷贝
c = a.copy()
a[0, 0] = 9
print(a)
print(c)
print(a is c)  # => False

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 2  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 2  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
True
[[ 9  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 2  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
False
